# This is a basic workflow to help you get started with Actions

name: Build Multiple Environments

on:
   push:
    branches:
    - jobs-artifacts-outputs
 
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      - name: Build Artifact
        run: echo "Build complet" > result.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
           name: build-result
           path: result.txt
      - name: Set version output
        id: set_version output
        run: echo "version=v1.0" >>$GITHUB_OUTPUT
   
   outputs:
    version: ${{ steps.set_version_output.outputs.version }}  

  print-version:
   runs-on: ubuntu-last
   needs: build
   steps:
     - name: Print version
       run: echo "The version is ${{ needs.build.outputs.version }}
